#! /usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

use GuzzleHttp\Client;
use App\Commands\Download;
use GuzzleHttp\Cookie\CookieJar;
use League\Flysystem\Filesystem;
use League\Flysystem\Adapter\Local;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Application;

try {
    $dotenv = new Dotenv();
    $dotenv->load(__DIR__ . '/.env');
} catch (\Symfony\Component\Dotenv\Exception\PathException $excption) {
    echo 'Unable to read the environment file, please create one first.' . PHP_EOL;
    exit(1);
}

$cookie = new CookieJar();
$client = new Client([
    'base_uri' => 'https://laracasts.com',
    'verify' => false,
//    'timeout' => 2.0,
    'allow_redirects' => ['track_redirects' => true],
    'cookies' => $cookie,
]);

$filesystem = new Filesystem(new Local(getenv('DOWNLOAD_DIR')));

$app = new Application('Laracasts Downloader', '0.1');
$app->add(new Download($client, $filesystem));

$app->setAutoExit(true);
$app->run();
